//------------------------------------------------------------------------------
// Types for /Users/mariomain/projects/star wars clone wars/extract_all/Clonewars.elf.bndb
//
// This header file generated by Binary Ninja Personal 4.3.6541-dev Personal
//------------------------------------------------------------------------------

#ifndef BN_TYPE_PARSER
#include <stdint.h>
#include <stddef.h>
#include <stdlib.h>
#include <stdbool.h>
#include <wchar.h>

#define __packed
#define __noreturn
#define __convention(name)
#define __syscall(number)
#define __offset(...)
#define __padding
#define __named(name)
#define __inherited
#define __base(name, offset)
#define __ptr_offset(offset)
#define __data_var_refs
#define __vtable
#define __pure
#define __ptr_width(width)
#define __ptr8
#define __ptr16
// __ptr32 and __ptr64 are real keywords on MSVC
// #define __ptr32
// #define __ptr64
#define __based(...)
typedef uint16_t wchar16;
typedef uint32_t wchar32;
#endif

//------------------------------------------------------------------------------
// Forward Declarations of Structures
//------------------------------------------------------------------------------

struct AllocatorNode;
struct Elf32_Header;
struct Elf32_Ident;
struct Elf32_ProgramHeader;
struct Elf32_SectionHeader;
struct FScope;
struct FunctionScope;
struct GameSimulation;
struct MeshItem;
struct NodeLevel1;
struct NodeLevel1Alternate;
struct NodeLevel1Secondary;
struct NodeLevel1Tertiary;
struct NodeLevel2;
struct NodeLevel2Alternate;
struct NodeLevel2Secondary;
struct NodeLevel2Tertiary;
struct NodeLevel3;
struct NodeLevel3Alternate;
struct NodeLevel3Secondary;
struct NodeLevel3Tertiary;
struct NodeLevel4Alternate;
struct NodeLevel4Secondary;
struct ObjectList;
struct ObjectSequence;
struct ObjectSequence_1;
struct SPMission;
struct SceneManager;
struct TeamController;
struct TerrainData;
struct TerrainObject;
struct TerrainPatch;
struct TextureObject;
struct TextureObject_1;
struct Timer;
struct TimerData;
struct Timer_1;
struct Timer_2;
struct VideoResource;
struct ZeroAllocatorContext;
struct raxusscript1_t;
struct raxusscript3_t;
struct struct_1;
struct struct_10;
struct struct_100;
struct struct_101;
struct struct_102;
struct struct_103;
struct struct_104;
struct struct_105;
struct struct_106;
struct struct_107;
struct struct_108;
struct struct_109;
struct struct_11;
struct struct_110;
struct struct_111;
struct struct_112;
struct struct_113;
struct struct_114;
struct struct_115;
struct struct_116;
struct struct_117;
struct struct_118;
struct struct_119;
struct struct_12;
struct struct_120;
struct struct_121;
struct struct_122;
struct struct_123;
struct struct_124;
struct struct_125;
struct struct_126;
struct struct_127;
struct struct_128;
struct struct_129;
struct struct_13;
struct struct_130;
struct struct_131;
struct struct_132;
struct struct_133;
struct struct_134;
struct struct_135;
struct struct_136;
struct struct_137;
struct struct_138;
struct struct_139;
struct struct_14;
struct struct_140;
struct struct_141;
struct struct_142;
struct struct_143;
struct struct_144;
struct struct_145;
struct struct_146;
struct struct_147;
struct struct_148;
struct struct_149;
struct struct_15;
struct struct_150;
struct struct_151;
struct struct_152;
struct struct_153;
struct struct_154;
struct struct_155;
struct struct_156;
struct struct_157;
struct struct_158;
struct struct_159;
struct struct_16;
struct struct_160;
struct struct_161;
struct struct_162;
struct struct_163;
struct struct_164;
struct struct_165;
struct struct_166;
struct struct_167;
struct struct_168;
struct struct_169;
struct struct_17;
struct struct_170;
struct struct_171;
struct struct_172;
struct struct_173;
struct struct_174;
struct struct_175;
struct struct_176;
struct struct_177;
struct struct_178;
struct struct_179;
struct struct_18;
struct struct_180;
struct struct_181;
struct struct_182;
struct struct_183;
struct struct_184;
struct struct_185;
struct struct_186;
struct struct_187;
struct struct_188;
struct struct_189;
struct struct_19;
struct struct_190;
struct struct_191;
struct struct_192;
struct struct_193;
struct struct_194;
struct struct_195;
struct struct_196;
struct struct_197;
struct struct_198;
struct struct_199;
struct struct_2;
struct struct_20;
struct struct_200;
struct struct_201;
struct struct_202;
struct struct_203;
struct struct_204;
struct struct_205;
struct struct_206;
struct struct_207;
struct struct_208;
struct struct_209;
struct struct_21;
struct struct_210;
struct struct_211;
struct struct_212;
struct struct_213;
struct struct_214;
struct struct_215;
struct struct_216;
struct struct_217;
struct struct_218;
struct struct_219;
struct struct_22;
struct struct_23;
struct struct_24;
struct struct_25;
struct struct_26;
struct struct_27;
struct struct_28;
struct struct_29;
struct struct_3;
struct struct_30;
struct struct_31;
struct struct_32;
struct struct_33;
struct struct_34;
struct struct_35;
struct struct_36;
struct struct_37;
struct struct_38;
struct struct_39;
struct struct_4;
struct struct_40;
struct struct_41;
struct struct_42;
struct struct_43;
struct struct_44;
struct struct_45;
struct struct_46;
struct struct_47;
struct struct_48;
struct struct_49;
struct struct_5;
struct struct_50;
struct struct_51;
struct struct_52;
struct struct_53;
struct struct_54;
struct struct_55;
struct struct_56;
struct struct_57;
struct struct_58;
struct struct_59;
struct struct_6;
struct struct_60;
struct struct_61;
struct struct_62;
struct struct_63;
struct struct_64;
struct struct_65;
struct struct_66;
struct struct_68;
struct struct_69;
struct struct_7;
struct struct_70;
struct struct_71;
struct struct_72;
struct struct_73;
struct struct_74;
struct struct_75;
struct struct_76;
struct struct_77;
struct struct_78;
struct struct_79;
struct struct_8;
struct struct_80;
struct struct_81;
struct struct_82;
struct struct_83;
struct struct_84;
struct struct_85;
struct struct_86;
struct struct_87;
struct struct_88;
struct struct_89;
struct struct_9;
struct struct_90;
struct struct_91;
struct struct_92;
struct struct_93;
struct struct_94;
struct struct_95;
struct struct_96;
struct struct_97;
struct struct_98;
struct struct_99;
//------------------------------------------------------------------------------
// Type Definitions
//------------------------------------------------------------------------------

// "AllocatorNode"
struct AllocatorNode
{
	__padding char _0[1];
	__padding char _1[2];
	char field_03;
	__padding char _4[4];
	void* leftChild;
	void* rightChild;
	struct AllocatorNode* field_10;
};

// "Elf32_Header"
struct Elf32_Header
{
	struct Elf32_Ident ident;
	enum e_type type;
	enum e_machine machine;
	uint32_t version;
	void (* entry)();
	uint32_t program_header_offset;
	uint32_t section_header_offset;
	uint32_t flags;
	uint16_t header_size;
	uint16_t program_header_size;
	uint16_t program_header_count;
	uint16_t section_header_size;
	uint16_t section_header_count;
	uint16_t string_table;
};

// "Elf32_Ident"
struct Elf32_Ident
{
	char signature[0x4];
	uint8_t file_class;
	uint8_t encoding;
	uint8_t version;
	uint8_t os;
	uint8_t abi_version;
	char pad[0x7];
};

// "Elf32_ProgramHeader"
struct Elf32_ProgramHeader
{
	enum p_type type;
	uint32_t offset;
	uint32_t virtual_address;
	uint32_t physical_address;
	uint32_t file_size;
	uint32_t memory_size;
	enum p_flags flags;
	uint32_t align;
};

// "Elf32_SectionHeader"
struct Elf32_SectionHeader
{
	uint32_t name;
	enum sh_type type;
	enum sh_flags flags;
	uint32_t address;
	uint32_t offset;
	uint32_t size;
	uint32_t link;
	uint32_t info;
	uint32_t align;
	uint32_t entry_size;
};

// "FScope"
struct FScope
{
	__padding char _0[4];
	__padding char _4[4];
	int32_t scopeIdentifier;
};

// "FunctionScope"
struct FunctionScope
{
	__padding char _0[4];
	__padding char _4[4];
	int32_t field_08;
	__padding char _C[4];
	int32_t field_10;
	__padding char _14[8];
	__padding char _1C[8];
	int32_t argumentCount;
	__padding char _28[8];
	int32_t currentArgument;
	struct struct_48* field_34;
	__padding char _38[4];
	__padding char _3C[4];
	__padding char _40[0xc];
	int32_t field_4c;
	struct struct_49* field_50;
	void* field_54;
};

// "GameSimulation"
struct GameSimulation
{
	__padding char _0[4];
	void* field_04;
	int32_t field_08;
	void* field_0c;
	void* field_10;
	void* field_14;
	void* field_18;
	int32_t field_1c;
	int32_t field_20;
	int32_t field_24;
	int32_t field_28;
	int32_t field_2c;
	int32_t field_30;
	int32_t field_34;
	int32_t field_38;
	int32_t field_3c;
	int32_t field_40;
	int32_t field_44;
	int32_t field_48;
	int32_t field_4c;
};

// "MeshItem"
struct MeshItem
{
	char field_00;
};

// "NodeLevel1"
struct NodeLevel1
{
	int32_t nodeType_1;
	int32_t field_04;
	struct NodeLevel1Alternate* previousNode;
	__padding char _C[4];
	struct NodeLevel2* nextNode_1;
};

// "NodeLevel1Alternate"
struct NodeLevel1Alternate
{
	int32_t nodeType_5;
	__padding char _4[4];
	struct NodeLevel4Alternate* previousNode_4;
	__padding char _C[4];
	struct NodeLevel3Alternate* nextNode_5;
};

// "NodeLevel1Secondary"
struct NodeLevel1Secondary
{
	int32_t nodeType_8;
	__padding char _4[4];
	struct NodeLevel1Tertiary* previousNode_7;
	__padding char _C[4];
	struct NodeLevel2Secondary* nextNode_8;
};

// "NodeLevel1Tertiary"
struct NodeLevel1Tertiary
{
	int32_t nodeType_12;
	__padding char _4[4];
	struct NodeLevel3Tertiary* previousNode_11;
	__padding char _C[4];
	struct NodeLevel2Tertiary* nextNode_12;
};

// "NodeLevel2"
struct NodeLevel2
{
	int32_t nodeType_2;
	int32_t field_04;
	struct NodeLevel2Alternate* previousNode_1;
	__padding char _C[4];
	struct NodeLevel3* nextNode_2;
};

// "NodeLevel2Alternate"
struct NodeLevel2Alternate
{
	int32_t nodeType_4;
	__padding char _4[4];
	struct TeamController* previousNode_3;
	__padding char _C[4];
	int32_t nextNode_4;
};

// "NodeLevel2Secondary"
struct NodeLevel2Secondary
{
	int32_t nodeType_9;
	__padding char _4[4];
	struct NodeLevel4Secondary* previousNode_8;
	__padding char _C[4];
	struct NodeLevel3Secondary* nextNode_9;
};

// "NodeLevel2Tertiary"
struct NodeLevel2Tertiary
{
	int32_t nodeType_13;
	__padding char _4[4];
	struct TeamController* previousNode_12;
	__padding char _C[4];
	int32_t nextNode_13;
};

// "NodeLevel3"
struct NodeLevel3
{
	int32_t nodeType_3;
	int32_t field_04;
	struct TeamController* previousNode_2;
	__padding char _C[4];
	struct TeamController* nextNode_3;
};

// "NodeLevel3Alternate"
struct NodeLevel3Alternate
{
	int32_t nodeType_6;
	__padding char _4[4];
	struct TeamController* previousNode_5;
	__padding char _C[4];
	int32_t nextNode_6;
};

// "NodeLevel3Secondary"
struct NodeLevel3Secondary
{
	int32_t nodeType_10;
	__padding char _4[4];
	struct TeamController* previousNode_9;
	__padding char _C[4];
	int32_t nextNode_10;
};

// "NodeLevel3Tertiary"
struct NodeLevel3Tertiary
{
	int32_t nodeType_14;
	__padding char _4[4];
	struct TeamController* previousNode_13;
	__padding char _C[4];
	int32_t nextNode_14;
};

// "NodeLevel4Alternate"
struct NodeLevel4Alternate
{
	int32_t nodeType_7;
	__padding char _4[4];
	struct TeamController* previousNode_6;
	__padding char _C[4];
	int32_t nextNode_7;
};

// "NodeLevel4Secondary"
struct NodeLevel4Secondary
{
	int32_t nodeType_11;
	__padding char _4[4];
	struct TeamController* previousNode_10;
	__padding char _C[4];
	int32_t nextNode_11;
};

// "ObjectList"
struct ObjectList
{
	int32_t field_00;
	__padding char _4[4];
	struct struct_78* field_08;
	__padding char _C[4];
	struct NodeLevel3Alternate* field_10;
};

// "ObjectSequence"
struct ObjectSequence
{
	int32_t field_00;
	int32_t commandHandler;
	int32_t field_08;
	__padding char _C[4];
	__padding char _10[4];
	__padding char _14[4];
	__padding char _18[4];
	__padding char _1C[4];
	__padding char _20[4];
	__padding char _24[4];
	__padding char _28[4];
	__padding char _2C[4];
	__padding char _30[4];
	__padding char _34[4];
	void* field_38;
};

// "ObjectSequence_1"
struct ObjectSequence_1
{
	__padding char _0[4];
	void* field_04;
};

// "SPMission"
struct SPMission
{
	void* vtable_DLLBase;
	int32_t missionID;
	int32_t status;
	int32_t priority;
	int32_t startTime;
	int32_t endTime;
	int32_t location;
	int32_t objectiveCount;
	int32_t isActive;
};

// "SceneManager"
struct SceneManager
{
	char statusFlags;
	void* virtualTablePointer;
};

// "TeamController"
struct TeamController
{
	int32_t nodeType;
	int32_t field_04;
	struct NodeLevel1Secondary* value;
	int32_t field_0c;
	struct NodeLevel1* nextNode;
};

// "TerrainData"
struct TerrainData
{
	__padding char _0[0x10];
	int32_t height;
	int32_t width;
	int32_t depth;
	__padding char _1C[4];
	int32_t textureID;
	int32_t color;
	int32_t lightIntensity;
	__padding char _2C[4];
	int32_t positionOffset;
	int32_t normal;
	int32_t tangent;
};

// "TerrainObject"
struct TerrainObject
{
	__padding char _0[0x40];
	void* quadTreeNode;
	__padding char _44[0x3c];
	__padding char _80[0x40];
	__padding char _C0[0xc];
	__padding char _CC[8];
	__padding char _D4[4];
	__padding char _D8[8];
	__padding char _E0[8];
	__padding char _E8[0x18];
	__padding char _100[0x40];
	__padding char _140[0x40];
	__padding char _180[0x2c];
	__padding char _1AC[4];
	int32_t position;
	__padding char _1B4[4];
	int32_t scale;
	int32_t mirrorScale;
	__padding char _1C0[4];
	int32_t rotation;
};

// "TerrainPatch"
struct TerrainPatch
{
	int32_t field_00;
	int32_t field_04;
	int32_t field_08;
	int32_t field_0c;
	int32_t field_10;
	int32_t field_14;
	__padding char _18[0x14];
	int32_t maxTextureCount;
	char textureIndices;
	__padding char _34[0xc];
	__padding char _40[0x10];
	int32_t vertexCount;
	void* vertexData;
};

// "TextureObject"
struct TextureObject
{
	int32_t textureData0;
	int32_t textureData1;
	int32_t textureData2;
	int32_t textureData3;
	__padding char _10[8];
	int32_t textureHandle;
	__padding char _1C[3];
	char flags;
};

// "TextureObject_1"
struct TextureObject_1
{
	__padding char _0[4];
	__padding char _4[4];
	int32_t unknownFlag;
	__padding char _C[4];
	__padding char _10[4];
	__padding char _14[4];
	__padding char _18[4];
	__padding char _1C[4];
	__padding char _20[4];
	__padding char _24[4];
	__padding char _28[4];
	__padding char _2C[4];
	__padding char _30[4];
	__padding char _34[4];
	__padding char _38[8];
	__padding char _40[4];
	__padding char _44[4];
	__padding char _48[4];
	__padding char _4C[4];
	__padding char _50[4];
	__padding char _54[4];
	__padding char _58[4];
	__padding char _5C[0x18];
	__padding char _74[0xc];
	__padding char _80[0x40];
	__padding char _C0[0x14];
	struct struct_139* field_d4;
};

// "Timer"
struct Timer
{
	int32_t startTime;
	int32_t duration;
	int32_t isActive;
};

// "TimerData"
struct TimerData
{
	int32_t startTime;
	int32_t elapsedTime;
	char isActive;
};

// "Timer_1"
struct Timer_1
{
	int32_t startTime;
	__padding char _4[4];
	char isRunning;
};

// "Timer_2"
struct Timer_2
{
	int32_t startTime;
	int32_t elapsedTime;
	char isRunning;
};

// "VideoResource"
struct VideoResource
{
	__padding char _0[4];
	void* field_04;
	__padding char _8[0x10];
	int32_t field_18;
	int16_t field_1c;
	int16_t field_1e;
	int16_t field_20;
	__padding char _22[0xf];
	char field_31;
	__padding char _32[0xe];
	__padding char _40[0xa];
	__padding char _4A[0xa];
	char field_54;
	char field_55;
	char field_56;
	char field_57;
	void* field_58;
	__padding char _5C[4];
	int32_t field_60;
	int32_t field_64;
	void* field_68;
	__padding char _6C[4];
	void* field_70;
	void* field_74;
};

// "ZeroAllocatorContext"
struct ZeroAllocatorContext
{
	__padding char _0[4];
	int32_t field_04;
	struct struct_201* field_08;
};

// "e_machine"
enum e_machine : uint16_t
{
	EM_NONE = 0x0,
	EM_M32 = 0x1,
	EM_SPARC = 0x2,
	EM_386 = 0x3,
	EM_68K = 0x4,
	EM_88K = 0x5,
	EM_860 = 0x7,
	EM_MIPS = 0x8,
	EM_S370 = 0x9,
	EM_MIPS_RS3_LE = 0xa,
	EM_PARISC = 0xf,
	EM_VPP500 = 0x11,
	EM_SPARC32PLUS = 0x12,
	EM_960 = 0x13,
	EM_PPC = 0x14,
	EM_PPC64 = 0x15,
	EM_S390 = 0x16,
	EM_V800 = 0x24,
	EM_FR20 = 0x25,
	EM_RH32 = 0x26,
	EM_RCE = 0x27,
	EM_ARM = 0x28,
	EM_FAKE_ALPHA = 0x29,
	EM_SH = 0x2a,
	EM_SPARCV9 = 0x2b,
	EM_TRICORE = 0x2c,
	EM_ARC = 0x2d,
	EM_H8_300 = 0x2e,
	EM_H8_300H = 0x2f,
	EM_H8S = 0x30,
	EM_H8_500 = 0x31,
	EM_IA_64 = 0x32,
	EM_MIPS_X = 0x33,
	EM_COLDFIRE = 0x34,
	EM_68HC12 = 0x35,
	EM_MMA = 0x36,
	EM_PCP = 0x37,
	EM_NCPU = 0x38,
	EM_NDR1 = 0x39,
	EM_STARCORE = 0x3a,
	EM_ME16 = 0x3b,
	EM_ST100 = 0x3c,
	EM_TINYJ = 0x3d,
	EM_X86_64 = 0x3e,
	EM_PDSP = 0x3f,
	EM_FX66 = 0x42,
	EM_ST9PLUS = 0x43,
	EM_ST7 = 0x44,
	EM_68HC16 = 0x45,
	EM_68HC11 = 0x46,
	EM_68HC08 = 0x47,
	EM_68HC05 = 0x48,
	EM_SVX = 0x49,
	EM_ST19 = 0x4a,
	EM_VAX = 0x4b,
	EM_CRIS = 0x4c,
	EM_JAVELIN = 0x4d,
	EM_FIREPATH = 0x4e,
	EM_ZSP = 0x4f,
	EM_MMIX = 0x50,
	EM_HUANY = 0x51,
	EM_PRISM = 0x52,
	EM_AVR = 0x53,
	EM_FR30 = 0x54,
	EM_D10V = 0x55,
	EM_D30V = 0x56,
	EM_V850 = 0x57,
	EM_M32R = 0x58,
	EM_MN10300 = 0x59,
	EM_MN10200 = 0x5a,
	EM_PJ = 0x5b,
	EM_OPENRISC = 0x5c,
	EM_ARC_A5 = 0x5d,
	EM_XTENSA = 0x5e,
	EM_ALTERA_NIOS2 = 0x71,
	EM_AARCH64 = 0xb7,
	EM_TILEPRO = 0xbc,
	EM_MICROBLAZE = 0xbd,
	EM_TILEGX = 0xbf,
	EM_NUM = 0xc0
};

// "e_type"
enum e_type : uint16_t
{
	ET_NONE = 0x0,
	ET_REL = 0x1,
	ET_EXEC = 0x2,
	ET_DYN = 0x3,
	ET_CORE = 0x4,
	ET_NUM = 0x5
};

// "p_flags"
enum p_flags : uint32_t
{
	PF_X = 0x1,
	PF_W = 0x2,
	PF_R = 0x4
};

// "p_type"
enum p_type : uint32_t
{
	PT_NULL = 0x0,
	PT_LOAD = 0x1,
	PT_DYNAMIC = 0x2,
	PT_INTERP = 0x3,
	PT_NOTE = 0x4,
	PT_SHLIB = 0x5,
	PT_PHDR = 0x6,
	PT_TLS = 0x7,
	PT_NUM = 0x8,
	PT_LOOS = 0x60000000,
	PT_GNU_EH_FRAME = 0x6474e550,
	PT_GNU_STACK = 0x6474e551,
	PT_GNU_RELRO = 0x6474e552,
	PT_GNU_PROPERTY = 0x6474e553,
	PT_LOSUNW = 0x6ffffffa,
	PT_SUNWBSS = 0x6ffffffb,
	PT_SUNWSTACK = 0x6ffffffa,
	PT_MIPS_REGINFO = 0x70000000,
	PT_MIPS_RTPROC = 0x70000001,
	PT_MIPS_OPTIONS = 0x70000002,
	PT_MIPS_ABIFLAGS = 0x70000003
};

// "raxusscript1_t"
struct __data_var_refs raxusscript1_t __packed
{
	void** vtable;
	char* missionStatusPointer;
	int32_t difficultyLevel;
	float* someFlag20Pointer;
	int32_t maxAttempts;
	struct ObjectSequence** someFlag40Pointer;
	int32_t timeoutDuration;
	int32_t* mainObjectivePointer;
	int32_t enemyCount;
	__padding char _24[1];
	char missionStatus;
	char hasCollector1Engaged;
	char hasCollector2Engaged;
	char isCollector1Moving;
	char isCollector2Moving;
	char isMissionActive;
	char isMusicPlaying;
	char isTransitioning;
	char isEnding;
	char isInitialized;
	char isPaused;
	char isStarted;
	char isCompleted;
	char isFailed;
	char isRunning;
	char isMissionFailed;
	char retryCount;
	char someOtherFlag;
	char anotherFlag;
	char yetAnotherFlag;
	char isObjectiveComplete;
	char isEnemy1Moving;
	char isEnemy1Stationary;
	char isPlayerInZone;
	char isEnemyDetected;
	char isTimerActive;
	char isCheckpointReached;
	char isGamePaused;
	char someStatusFlag;
	char someVisibilityFlag2;
	char isPlayerInCombat;
	char isObjectiveFailed;
	char someTimerFlag;
	char someCompletionFlag;
	char someCompletionFlag2;
	char someCompletionFlag3;
	char someCompletionFlag4;
	char someCompletionFlag5;
	__padding char _4B[0xa];
	char someCompletionFlag16;
	char someCompletionFlag17;
	char someCompletionFlag18;
	char someCompletionFlag19;
	char someCompletionFlag20;
	char someCompletionFlag21;
	char someCompletionFlag22;
	char someCompletionFlag23;
	char someCompletionFlag24;
	char someCompletionFlag25;
	char someCompletionFlag26;
	char someCompletionFlag27;
	char someCompletionFlag28;
	char someCompletionFlag29;
	char someCompletionFlag30;
	char someCompletionFlag31;
	char someCompletionFlag32;
	char shortcut1Flag;
	char shortcut2Flag;
	char bonusObjectiveCompleteFlag;
	char someFlag1;
	char someFlag2;
	char someFlag3;
	char someFlag4;
	char someFlag5;
	char someFlag6;
	char someFlag7;
	char someFlag8;
	__padding char _71[1];
	char someFlag10;
	char someFlag11;
	char someFlag12;
	char someFlag13;
	__padding char _76[6];
	float someFlag20;
	float someFlag24;
	float someFlag28;
	__padding char _88[8];
	struct ObjectSequence* handle_missutil[0xa];
	int32_t handle_player[0x4];
	struct ObjectSequence* handle_missuti_2;
	int32_t someFlag94;
	int32_t someFlag98;
	int32_t someFlag102;
	struct ObjectSequence* bike_speeder_player_small;
	struct ObjectSequence* bike_speeder_anakin;
	struct ObjectSequence* bike_speeder_player_small1;
	struct ObjectSequence* bike_speeder_anakin1;
	struct ObjectSequence* CIS_bike_speeder_large1;
	struct ObjectSequence* CIS_bike_speeder_large2;
	struct ObjectSequence* CIS_bike_speeder_large3;
	struct ObjectSequence* CIS_bike_speeder_large4;
	struct ObjectSequence* CIS_bike_speeder_large5;
	struct ObjectSequence* CIS_bike_speeder_large6;
	struct ObjectSequence* CIS_bike_speeder_large7;
	struct ObjectSequence* rep_fly_fighter;
	struct ObjectSequence* rep_fly_fighter1;
	struct ObjectSequence* rep_fly_fighter2;
	struct ObjectSequence* rep_fly_fighter3;
	struct ObjectSequence* craneObject;
	int32_t obiWanObject;
	struct ObjectSequence* anakinObject;
	struct ObjectSequence* bike_speeder_anakin1_1;
	struct ObjectSequence* inf_anakin_cin2;
	__padding char _128[4];
	struct ObjectSequence* bike_speeder_large;
	__padding char _130[4];
	int32_t craneObject1;
	struct ObjectSequence* cis_fly_fighter1;
	struct ObjectSequence* cis_fly_fighter2;
	struct ObjectSequence* cis_fly_fighter3;
	struct ObjectSequence* cis_fly_fighter4;
	struct ObjectSequence* CIS_fly_technounion_rax3_5;
	struct ObjectSequence* handle_missutil_1[0x3];
	__padding char _158[8];
	int32_t mainObjective;
	int32_t buffer[0xe];
	struct Timer rs1timers[0x10];
};

// "raxusscript3_t"
struct __data_var_refs raxusscript3_t __packed
{
	void** vtable;
	struct struct_17* somePointerField;
	int32_t status;
	struct struct_17* pointerToFieldAC;
	int32_t isActive;
	struct struct_17* anotherPointerField;
	int32_t missionID;
	struct struct_17* taskPointer;
	int32_t difficultyLevel;
	__padding char _24[1];
	int32_t nextMissionPointer;
	char bonusObjectiveFailed1;
	char bonusObjectiveFailed2;
	__padding char _2B[1];
	__padding char _2C[1];
	__padding char _2D[1];
	__padding char _2E[1];
	__padding char _2F[1];
	char isInitialized;
	char isActive_1;
	char isVisible;
	char isEnabled;
	__padding char _34[1];
	char isMusicEnabled;
	__padding char _36[1];
	__padding char _37[1];
	__padding char _38[1];
	__padding char _39[1];
	__padding char _3A[1];
	__padding char _3B[1];
	__padding char _3C[1];
	__padding char _3D[1];
	__padding char _3E[1];
	__padding char _3F[1];
	__padding char _40[1];
	__padding char _41[1];
	__padding char _42[1];
	__padding char _43[1];
	__padding char _44[1];
	__padding char _45[1];
	__padding char _46[2];
	__padding char _48[1];
	__padding char _49[1];
	char musicLoopingEnabled;
	__padding char _4B[1];
	__padding char _4C[1];
	__padding char _4D[1];
	__padding char _4E[1];
	__padding char _4F[1];
	__padding char _50[1];
	__padding char _51[1];
	__padding char _52[1];
	__padding char _53[1];
	__padding char _54[1];
	__padding char _55[1];
	__padding char _56[1];
	__padding char _57[2];
	__padding char _59[1];
	__padding char _5A[1];
	__padding char _5B[1];
	__padding char _5C[2];
	__padding char _5E[1];
	__padding char _5F[1];
	__padding char _60[1];
	__padding char _61[1];
	__padding char _62[1];
	__padding char _63[1];
	__padding char _64[1];
	__padding char _65[1];
	__padding char _66[1];
	__padding char _67[1];
	__padding char _68[1];
	__padding char _69[1];
	__padding char _6A[1];
	__padding char _6B[1];
	__padding char _6C[1];
	__padding char _6D[1];
	__padding char _6E[1];
	__padding char _6F[1];
	__padding char _70[2];
	__padding char _72[2];
	__padding char _74[1];
	__padding char _75[1];
	__padding char _76[1];
	__padding char _77[1];
	__padding char _78[1];
	__padding char _79[1];
	__padding char _7A[1];
	__padding char _7B[1];
	__padding char _7C[1];
	__padding char _7D[1];
	__padding char _7E[1];
	__padding char _7F[1];
	__padding char _80[1];
	__padding char _81[1];
	__padding char _82[1];
	__padding char _83[1];
	__padding char _84[1];
	__padding char _85[1];
	__padding char _86[1];
	__padding char _87[1];
	__padding char _88[1];
	__padding char _89[1];
	__padding char _8A[1];
	__padding char _8B[1];
	__padding char _8C[1];
	__padding char _8D[1];
	__padding char _8E[1];
	__padding char _8F[1];
	__padding char _90[1];
	__padding char _91[1];
	__padding char _92[1];
	__padding char _93[1];
	__padding char _94[2];
	__padding char _96[1];
	__padding char _97[1];
	char playerDead;
	__padding char _99[1];
	__padding char _9A[1];
	__padding char _9B[1];
	__padding char _9C[1];
	__padding char _9D[1];
	__padding char _9E[1];
	__padding char _9F[1];
	__padding char _A0[1];
	__padding char _A1[1];
	__padding char _A2[1];
	__padding char _A3[1];
	char missionFailed;
	__padding char _A5[7];
	int32_t pointerToFieldAC_1;
	__padding char _B0[8];
	int32_t anotherPointerField_1;
	int32_t deathCinematic;
	__padding char _C0[4];
	__padding char _C4[4];
	__padding char _C8[4];
	__padding char _CC[4];
	int32_t mainObjective;
	__padding char _D4[4];
	__padding char _D8[4];
	__padding char _DC[4];
	__padding char _E0[4];
	int32_t bonusObjective3;
	int32_t bonusObjective2;
	int32_t bonusObjective1;
	__padding char _F0[4];
	__padding char _F4[4];
	int32_t openCinsixLeg1Handle;
	int32_t openCinsixLeg2Handle;
	int32_t openCinsixLeg3Handle;
	__padding char _104[4];
	int32_t openCinWalker1Handle;
	int32_t openCinWalker2Handle;
	int32_t openCinWalker4Handle;
	int32_t openCinWalker5Handle;
	int32_t openCinWalker6Handle;
	int32_t openCinWalker7Handle;
	int32_t openCingunship1Handle;
	int32_t openCingunship2Handle;
	int32_t openCinTank1Handle;
	int32_t openCinTank2Handle;
	int32_t openCinTank3Handle;
	__padding char _134[4];
	__padding char _138[4];
	int32_t openCinAnakinHandle;
	__padding char _140[4];
	uint32_t playerHandle;
	int32_t playerTankHandle;
	struct ObjectSequence* playerObject1;
	int32_t field_150;
	__padding char _154[4];
	struct ObjectSequence* playerObject2;
	int32_t tempSquad1Handle;
	int32_t tempSquad2Handle;
	__padding char _164[0xc];
	struct ObjectSequence* attackObject;
	int32_t enemyHandle1;
	int32_t enemyHandle2;
	int32_t enemyHandle3;
	int32_t enemyHandle4;
	int32_t enemyHandle5;
	int32_t enemyHandle6;
	int32_t enemyHandle7;
	int32_t enemyHandle8;
	int32_t enemyHandle9;
	int32_t enemyHandle10;
	int32_t enemyHandle11;
	int32_t enemyHandle12;
	int32_t enemyHandle13;
	int32_t enemyHandle14;
	int32_t enemyHandle15;
	int32_t enemyHandle16;
	int32_t enemyHandle17;
	int32_t enemyHandle18;
	int32_t enemyHandle19;
	int32_t enemyHandle20;
	int32_t openingJunkHandle;
	int32_t wallHandle1;
	int32_t wallHandle2;
	int32_t wallHandle3;
	int32_t wallHandle4;
	int32_t wallHandle5;
	int32_t wallHandle6;
	int32_t wallHandle7;
	__padding char _1E4[0x1c];
	__padding char _200[0x2c];
	int32_t attackStage1Handle;
	int32_t attackStage2Handle;
	int32_t attackStage3Handle;
	int32_t attackStage4Handle;
	__padding char _23C[4];
	int32_t attackStage5Handle;
	int32_t attackStage6Handle;
	int32_t attackStage7Handle;
	int32_t attackStage8Handle;
	__padding char _250[4];
	int32_t attackFighter1Handle;
	int32_t attackFighter2Handle;
	int32_t attackFighter3Handle;
	__padding char _260[4];
	struct ObjectSequence* objectToHide4;
	struct ObjectSequence* objectToHide5;
	struct ObjectSequence* objectToHide6;
	__padding char _270[4];
	struct ObjectSequence* objectToHide1;
	struct ObjectSequence* objectToHide2;
	struct ObjectSequence* objectToHide3;
	__padding char _280[4];
	__padding char _284[4];
	int32_t enemyMover1;
	int32_t enemyMover2;
	int32_t enemyMover3;
	int32_t enemyMover4;
	int32_t attackAssault1Handle;
	int32_t attackAssault2Handle;
	int32_t attackAssault3Handle;
	__padding char _2A4[4];
	__padding char _2A8[4];
	__padding char _2AC[4];
	__padding char _2B0[4];
	__padding char _2B4[4];
	__padding char _2B8[4];
	__padding char _2BC[4];
	__padding char _2C0[4];
	__padding char _2C4[4];
	__padding char _2C8[4];
	__padding char _2CC[4];
	__padding char _2D0[4];
	__padding char _2D4[4];
	__padding char _2D8[4];
	__padding char _2DC[4];
	__padding char _2E0[4];
	__padding char _2E4[4];
	__padding char _2E8[4];
	__padding char _2EC[4];
	__padding char _2F0[4];
	__padding char _2F4[4];
	__padding char _2F8[4];
	__padding char _2FC[4];
	__padding char _300[0x14];
	struct ObjectSequence* enemy1;
	struct ObjectSequence* enemy2;
	struct ObjectSequence* enemy3;
	int32_t enemyHandle24;
	struct ObjectSequence* enemyFlock;
	struct ObjectSequence* flockMember2;
	struct ObjectSequence* flockMember1;
	struct ObjectSequence* flockMember3;
	struct ObjectSequence* flockMember4;
	struct ObjectSequence* flockMember5;
	struct ObjectSequence* flockMember6;
	struct ObjectSequence* flockMember7;
	struct ObjectSequence* objectToStop1;
	struct ObjectSequence* objectToStop2;
	struct ObjectSequence* objectToStop3;
	struct ObjectSequence* objectToStop4;
	__padding char _354[4];
	__padding char _358[4];
	__padding char _35C[4];
	__padding char _360[4];
	__padding char _364[4];
	__padding char _368[4];
	__padding char _36C[4];
	__padding char _370[4];
	__padding char _374[4];
	__padding char _378[4];
	__padding char _37C[4];
	__padding char _380[4];
	__padding char _384[4];
	__padding char _388[4];
	__padding char _38C[4];
	__padding char _390[4];
	__padding char _394[4];
	__padding char _398[4];
	__padding char _39C[4];
	__padding char _3A0[4];
	__padding char _3A4[4];
	__padding char _3A8[4];
	__padding char _3AC[4];
	__padding char _3B0[4];
	int32_t wallTower1Handle;
	int32_t wallTower2Handle;
	int32_t wallTower3Handle;
	int32_t wallTower4Handle;
	int32_t forceWall1Handle;
	int32_t forceWall2Handle;
	int32_t area2Wall1Handle;
	int32_t area2Wall2Handle;
	int32_t area2Wall3Handle;
	int32_t area2Wall4Handle;
	int32_t area2Wall5Handle;
	int32_t area2Wall6Handle;
	int32_t a2Walker1Handle;
	int32_t a2Walker2Handle;
	int32_t a2Walker3Handle;
	int32_t a2Walker4Handle;
	__padding char _3F4[4];
	__padding char _3F8[4];
	__padding char _3FC[4];
	__padding char _400[4];
	int32_t a2Fighter5Handle;
	int32_t a2Walker5Handle;
	int32_t a2Assault1Handle;
	int32_t a2Assault2Handle;
	int32_t a2WaitFighter1Handle;
	int32_t a2WaitFighter2Handle;
	int32_t a2WaitFighter3Handle;
	int32_t a2WaitFighter4Handle;
	int32_t a2WaitFighter5Handle;
	int32_t a2WaitFighter6Handle;
	int32_t a2WaitFighter7Handle;
	int32_t a2WaitFighter8Handle;
	int32_t a2WaitFighter9Handle;
	int32_t excavatorWallHandle;
	__padding char _43C[4];
	__padding char _440[4];
	__padding char _444[4];
	__padding char _448[4];
	__padding char _44C[4];
	__padding char _450[4];
	__padding char _454[4];
	__padding char _458[4];
	__padding char _45C[8];
	int32_t protoCinSixLeg1Handle;
	int32_t protoCinSixLeg2Handle;
	int32_t protoCinSixLeg3Handle;
	int32_t protoCinWalker1Handle;
	int32_t protoCinWalker2Handle;
	__padding char _478[4];
	int32_t unknownHandle1;
	int32_t unknownHandle2;
	int32_t sgennodeHandle;
	int32_t a3SixLeg1Handle;
	int32_t a3SixLeg2Handle;
	int32_t a3SixLeg3Handle;
	int32_t a3SixLeg4Handle;
	int32_t a3SixLeg5Handle;
	__padding char _49C[4];
	int32_t repWalker1Handle;
	int32_t repWalker2Handle;
	int32_t repWalker3Handle;
	int32_t repWalker4Handle;
	int32_t c1Fighter1Handle;
	int32_t c1Fighter2Handle;
	int32_t c1Fighter3Handle;
	int32_t c1Assault1Handle;
	int32_t c1Walker1Handle;
	int32_t c1Walker2Handle;
	__padding char _4C8[8];
	int32_t c2Fighter1Handle;
	int32_t c2Fighter2Handle;
	int32_t c2Fighter3Handle;
	int32_t c2Assault1Handle;
	int32_t c2Walker1Handle;
	int32_t c2Walker2Handle;
	__padding char _4E8[8];
	int32_t c3Walker1Handle;
	int32_t c3Walker2Handle;
	int32_t c3Tread1Handle;
	int32_t c3Tread2Handle;
	__padding char _500[4];
	__padding char _504[4];
	__padding char _508[4];
	__padding char _50C[4];
	int32_t a3Mortar1Handle;
	int32_t a3Mortar2Handle;
	int32_t a3Mortar3Handle;
	__padding char _51C[4];
	__padding char _520[4];
	__padding char _524[8];
	int32_t a3Walker1Handle;
	int32_t a3Walker2Handle;
	int32_t a3Walker3Handle;
	int32_t a3Walker4Handle;
	int32_t unknownHandle3;
	int32_t unknownHandle4;
	__padding char _544[4];
	struct ObjectSequence* objectToStop5;
	__padding char _54C[4];
	__padding char _550[4];
	__padding char _554[8];
	__padding char _55C[4];
	__padding char _560[4];
	__padding char _564[4];
	__padding char _568[4];
	__padding char _56C[4];
	__padding char _570[4];
	__padding char _574[4];
	int32_t protoDekaWallHandle;
	__padding char _57C[4];
	__padding char _580[4];
	__padding char _584[4];
	__padding char _588[4];
	__padding char _58C[4];
	__padding char _590[4];
	__padding char _594[4];
	int32_t protoTechnoShipHandle;
	__padding char _59C[4];
	__padding char _5A0[4];
	__padding char _5A4[4];
	int32_t building1Handle;
	int32_t building2Handle;
	__padding char _5B0[4];
	__padding char _5B4[4];
	__padding char _5B8[8];
	__padding char _5C0[8];
	int32_t taskPointer_1;
	__padding char _5CC[4];
	int32_t scriptPhase;
	__padding char _5D4[4];
	int32_t timer1;
	__padding char _5DC[8];
	int32_t timer2;
	__padding char _5E8[8];
	int32_t timer3;
	__padding char _5F4[8];
	int32_t timer4;
	__padding char _600[8];
	int32_t timer5;
	__padding char _60C[8];
	int32_t timer6;
	__padding char _618[8];
	int32_t timer7;
	__padding char _624[8];
	int32_t timer8;
	__padding char _630[8];
	int32_t timer9;
	__padding char _63C[4];
	__padding char _640[4];
	int32_t timer10;
	__padding char _648[8];
	int32_t timer11;
	__padding char _654[8];
	int32_t timer12;
	__padding char _660[8];
	int32_t timer13;
	__padding char _66C[8];
	int32_t timer14;
	__padding char _678[8];
	int32_t timer15;
	__padding char _684[8];
	int32_t timer16;
	__padding char _690[8];
	int32_t timer17;
	__padding char _69C[8];
	int32_t timer18;
	__padding char _6A8[8];
	int32_t timer19;
	__padding char _6B4[8];
	int32_t timer20;
	__padding char _6C0[8];
	int32_t timer21;
	__padding char _6CC[8];
	int32_t timer22;
	__padding char _6D8[8];
	int32_t timer23;
	__padding char _6E4[8];
	int32_t timer24;
	__padding char _6F0[8];
	int32_t timer25;
	__padding char _6FC[4];
	__padding char _700[4];
	int32_t timer26;
	__padding char _708[8];
	int32_t timer27;
	__padding char _714[8];
	int32_t timer28;
	__padding char _720[8];
	int32_t timer29;
	__padding char _72C[8];
	int32_t timer30;
	__padding char _738[8];
	int32_t timer31;
	__padding char _744[8];
	int32_t timer32;
	__padding char _750[8];
	int32_t timer33;
	__padding char _75C[8];
	int32_t timer34;
	__padding char _768[8];
	int32_t timer35;
	__padding char _774[8];
	int32_t timer36;
	__padding char _780[8];
	int32_t timer37;
	__padding char _78C[8];
	int32_t timer38;
	__padding char _798[8];
	int32_t timer39;
	__padding char _7A4[8];
	int32_t missionCheckpoint;
};

// "sh_flags"
enum sh_flags : uint32_t
{
	SHF_WRITE = 0x1,
	SHF_ALLOC = 0x2,
	SHF_EXECINSTR = 0x4,
	SHF_MERGE = 0x10,
	SHF_STRINGS = 0x20,
	SHF_INFO_LINK = 0x40,
	SHF_LINK_ORDER = 0x80,
	SHF_OS_NONCONFORMING = 0x100,
	SHF_GROUP = 0x200,
	SHF_TLS = 0x400,
	SHF_COMPRESSED = 0x800,
	SHF_MASKOS = 0xff00000,
	SHF_MASKPROC = 0xf0000000
};

// "sh_type"
enum sh_type : uint32_t
{
	SHT_NULL = 0x0,
	SHT_PROGBITS = 0x1,
	SHT_SYMTAB = 0x2,
	SHT_STRTAB = 0x3,
	SHT_RELA = 0x4,
	SHT_HASH = 0x5,
	SHT_DYNAMIC = 0x6,
	SHT_NOTE = 0x7,
	SHT_NOBITS = 0x8,
	SHT_REL = 0x9,
	SHT_SHLIB = 0xa,
	SHT_DYNSYM = 0xb,
	SHT_LOUSER = 0x80000000,
	SHT_HIUSER = 0xffffffff,
	SHT_LOPROC = 0x70000000,
	SHT_HIPROC = 0x7fffffff
};

// "struct_1"
struct struct_1
{
	__padding char _0[8];
	struct struct_1* field_08;
	struct struct_1* field_0c;
	__padding char _10[4];
	int32_t field_14;
	struct ObjectSequence* field_18;
};

// "struct_10"
struct struct_10
{
	__padding char _0[4];
	int32_t field_04;
	struct struct_11* field_08;
};

// "struct_100"
struct struct_100
{
	char field_00;
	char field_01;
	char field_02;
};

// "struct_101"
struct struct_101
{
	int32_t field_00;
	int32_t field_04;
	int32_t field_08;
};

// "struct_102"
struct struct_102
{
	__padding char _0[4];
	void* field_04;
	int32_t field_08;
	int32_t field_0c;
	int32_t field_10;
	int32_t field_14;
	int32_t field_18;
	int32_t field_1c;
	int32_t field_20;
	int32_t field_24;
	int32_t field_28;
	int32_t field_2c;
	int32_t field_30;
	int32_t field_34;
	int32_t field_38;
	int32_t field_3c;
	void* field_40;
	struct struct_193* field_44;
	__padding char _48[0x38];
	__padding char _80[0x40];
	__padding char _C0[8];
	int32_t field_c8;
	void* field_cc;
	void* field_d0;
	int32_t field_d4;
	int32_t field_d8;
	char field_dc;
	int32_t field_e0;
	int32_t field_e4;
	int32_t field_e8;
	int32_t field_ec;
	int32_t field_f0;
	int32_t field_f4;
	int32_t field_f8;
	int32_t field_fc;
	int32_t field_100;
	int32_t field_104;
	int32_t field_108;
	int32_t field_10c;
	int32_t field_110;
	__padding char _114[0x2c];
	__padding char _140[0x14];
	char field_154;
	int32_t field_158;
	int32_t field_15c;
	int32_t field_160;
	char field_164;
	int32_t field_168;
};

// "struct_103"
struct struct_103
{
	__padding char _0[0x40];
	__padding char _40[0x3c];
	int32_t field_7c;
	__padding char _80[0x14];
	int32_t field_94;
	int32_t field_98;
};

// "struct_104"
struct struct_104
{
	char field_00;
	char field_01;
	char field_02;
	char field_03;
};

// "struct_105"
struct struct_105
{
	char field_00;
	char field_01;
	char field_02;
	char field_03;
};

// "struct_106"
struct struct_106
{
	char field_00;
	char field_01;
	char field_02;
};

// "struct_107"
struct struct_107
{
	int16_t field_00;
	int16_t field_02;
	int16_t field_04;
};

// "struct_108"
struct struct_108
{
	__padding char _0[0x10];
	int32_t field_10;
};

// "struct_109"
struct struct_109
{
	int32_t field_00;
	int32_t field_04;
	int32_t field_08;
	int32_t field_0c;
	__padding char _10[4];
	int32_t field_14;
	__padding char _18[4];
	int16_t field_1c;
	char field_1e;
	char field_1f;
};

// "struct_11"
struct struct_11
{
	__padding char _0[0xc];
	int32_t field_0c;
};

// "struct_110"
struct struct_110
{
	int32_t field_00;
	int32_t field_04;
};

// "struct_111"
struct struct_111
{
	__padding char _0[0x14];
	int32_t field_14;
};

// "struct_112"
struct struct_112
{
	int32_t field_00;
	int32_t field_04;
};

// "struct_113"
struct struct_113
{
	int32_t field_00;
};

// "struct_114"
struct struct_114
{
	int32_t field_00;
};

// "struct_115"
struct struct_115
{
	int32_t field_00;
};

// "struct_116"
struct struct_116
{
	int32_t field_00;
};

// "struct_117"
struct struct_117
{
	int32_t field_00;
};

// "struct_118"
struct struct_118
{
	bool field_00;
};

// "struct_119"
struct struct_119
{
	char field_00;
};

// "struct_12"
struct struct_12
{
	int32_t field_00;
	int32_t field_04;
	int32_t field_08;
};

// "struct_120"
struct struct_120
{
	int32_t field_00;
};

// "struct_121"
struct struct_121
{
	__padding char _0[4];
	void* field_04;
	int32_t field_08;
	int32_t field_0c;
	int32_t field_10;
	int32_t field_14;
	int32_t field_18;
	int32_t field_1c;
	int32_t field_20;
	int32_t field_24;
	int32_t field_28;
	int32_t field_2c;
	int32_t field_30;
	int32_t field_34;
	int32_t field_38;
	int32_t field_3c;
	int32_t field_40;
	int32_t field_44;
	int32_t field_48;
	int32_t field_4c;
	int32_t field_50;
	int32_t field_54;
	int32_t field_58;
	int32_t field_5c;
	int32_t field_60;
	int32_t field_64;
	int32_t field_68;
	int32_t field_6c;
	int32_t field_70;
	int32_t field_74;
	int32_t field_78;
	int32_t field_7c;
	int32_t field_80;
	int32_t field_84;
	int32_t field_88;
	int32_t field_8c;
	int32_t field_90;
	int32_t field_94;
	int32_t field_98;
	int32_t field_9c;
	int32_t field_a0;
	int32_t field_a4;
	int32_t field_a8;
	int32_t field_ac;
	int32_t field_b0;
	int32_t field_b4;
	int32_t field_b8;
	__padding char _BC[4];
	__padding char _C0[0x40];
	__padding char _100[0x1c];
	int32_t field_11c;
	int32_t field_120;
	int32_t field_124;
	__padding char _128[0x18];
	__padding char _140[0x18];
	__padding char _158[0x28];
	__padding char _180[8];
	__padding char _188[0x30];
	__padding char _1B8[8];
	__padding char _1C0[0x40];
	__padding char _200[0x18];
	int32_t field_218;
	int32_t field_21c;
	int32_t field_220;
	int32_t field_224;
	int32_t field_228;
	int32_t field_22c;
	int32_t field_230;
	int32_t field_234;
	char field_238;
	__padding char _239[3];
	__padding char _23C[4];
	__padding char _240[4];
	__padding char _244[4];
	__padding char _248[4];
	__padding char _24C[4];
	__padding char _250[4];
	__padding char _254[4];
	__padding char _258[4];
	__padding char _25C[4];
	__padding char _260[4];
	__padding char _264[4];
	__padding char _268[4];
	__padding char _26C[4];
	__padding char _270[4];
	__padding char _274[4];
	__padding char _278[4];
	__padding char _27C[4];
	__padding char _280[4];
	__padding char _284[4];
	__padding char _288[4];
	__padding char _28C[4];
	__padding char _290[4];
	__padding char _294[4];
	__padding char _298[4];
	__padding char _29C[4];
	__padding char _2A0[4];
	char field_2a4;
	int32_t field_2a8;
	int32_t field_2ac;
	int32_t field_2b0;
	int32_t field_2b4;
	int32_t field_2b8;
	int32_t field_2bc;
	int32_t field_2c0;
	int32_t field_2c4;
};

// "struct_122"
struct struct_122
{
	__padding char _0[4];
	__padding char _4[8];
	__padding char _C[1];
	__padding char _D[3];
	int32_t field_10;
	int32_t field_14;
	void* field_18;
	int32_t field_1c;
};

// "struct_123"
struct struct_123
{
	int32_t field_00;
};

// "struct_124"
struct struct_124
{
	__padding char _0[4];
	struct struct_125* field_04;
};

// "struct_125"
struct struct_125
{
	__padding char _0[0x40];
	__padding char _40[0x40];
	__padding char _80[0x40];
	__padding char _C0[0x18];
	int32_t field_d8;
};

// "struct_126"
struct struct_126
{
	__padding char _0[4];
	struct struct_127* field_04;
	__padding char _8[0x38];
	__padding char _40[0x3c];
	int32_t field_7c;
	__padding char _80[0x10];
	int32_t field_90;
	__padding char _94[0x10];
	int32_t field_a4;
	int32_t field_a8;
	__padding char _AC[8];
	int32_t field_b4;
	int32_t field_b8;
	int32_t field_bc;
	int32_t field_c0;
	int32_t field_c4;
	int32_t field_c8;
	int32_t field_cc;
	int32_t field_d0;
	int32_t field_d4;
	int32_t field_d8;
	int32_t field_dc;
	int32_t field_e0;
	int32_t field_e4;
	int32_t field_e8;
	int32_t field_ec;
	int32_t field_f0;
	int32_t field_f4;
	int32_t field_f8;
	int32_t field_fc;
	int32_t field_100;
	int32_t field_104;
	int32_t field_108;
	int32_t field_10c;
	int32_t field_110;
	int32_t field_114;
	int32_t field_118;
	__padding char _11C[0x24];
	__padding char _140[0x18];
	int32_t field_158;
	int32_t field_15c;
	int32_t field_160;
	int32_t field_164;
	int32_t field_168;
	int32_t field_16c;
	int32_t field_170;
	int32_t field_174;
	int32_t field_178;
	int32_t field_17c;
	int32_t field_180;
	int32_t field_184;
	int32_t field_188;
	int32_t field_18c;
	int32_t field_190;
	int32_t field_194;
	int32_t field_198;
	int32_t field_19c;
	int32_t field_1a0;
	int32_t field_1a4;
	int32_t field_1a8;
	int32_t field_1ac;
	int32_t field_1b0;
	int32_t field_1b4;
	__padding char _1B8[8];
	__padding char _1C0[0x40];
	__padding char _200[0x30];
	int32_t field_230;
	__padding char _234[0xc];
	__padding char _240[0x40];
	__padding char _280[0x28];
	__padding char _2A8[4];
	__padding char _2AC[4];
	__padding char _2B0[4];
	__padding char _2B4[4];
	int32_t field_2b8;
	int32_t field_2bc;
	__padding char _2C0[8];
	int32_t field_2c8;
	int32_t field_2cc;
	int32_t field_2d0;
	int32_t field_2d4;
	int32_t field_2d8;
	int32_t field_2dc;
	int32_t field_2e0;
	int32_t field_2e4;
};

// "struct_127"
struct struct_127
{
	__padding char _0[0x40];
	__padding char _40[0x40];
	__padding char _80[0x20];
	int32_t field_a0;
};

// "struct_128"
struct struct_128
{
	__padding char _0[4];
	struct struct_129* field_04;
	__padding char _8[0x38];
	__padding char _40[0x40];
	__padding char _80[0x40];
	__padding char _C0[0x40];
	__padding char _100[0x40];
	__padding char _140[0x40];
	__padding char _180[0x40];
	__padding char _1C0[0x40];
	__padding char _200[0x40];
	__padding char _240[0x40];
	__padding char _280[0x28];
	__padding char _2A8[4];
	__padding char _2AC[4];
	__padding char _2B0[4];
	__padding char _2B4[4];
	int32_t field_2b8;
	int32_t field_2bc;
	int32_t field_2c0;
	int32_t field_2c4;
};

// "struct_129"
struct struct_129
{
	__padding char _0[0x40];
	__padding char _40[0x38];
	int32_t field_78;
	int32_t field_7c;
};

// "struct_13"
struct struct_13
{
	__padding char _0[4];
	struct struct_14* field_04;
};

// "struct_130"
struct struct_130
{
	__padding char _0[4];
	struct struct_131* field_04;
	__padding char _8[0x38];
	__padding char _40[0x40];
	__padding char _80[0x40];
	__padding char _C0[0x40];
	__padding char _100[0x40];
	__padding char _140[0x40];
	__padding char _180[0x40];
	__padding char _1C0[0x40];
	__padding char _200[0x40];
	__padding char _240[0x40];
	__padding char _280[0x38];
	int32_t field_2b8;
	int32_t field_2bc;
	int32_t field_2c0;
	int32_t field_2c4;
	int32_t field_2c8;
	__padding char _2CC[0x10];
	int32_t field_2dc;
	int32_t field_2e0;
	int32_t field_2e4;
};

// "struct_131"
struct struct_131
{
	__padding char _0[0x40];
	__padding char _40[0x40];
	__padding char _80[0xc];
	int32_t field_8c;
};

// "struct_132"
struct struct_132
{
	__padding char _0[4];
	struct struct_133* field_04;
	__padding char _8[0x38];
	__padding char _40[0x40];
	__padding char _80[0x40];
	__padding char _C0[0x40];
	__padding char _100[0x40];
	__padding char _140[0x40];
	__padding char _180[0x40];
	__padding char _1C0[0x40];
	__padding char _200[0x30];
	int32_t field_230;
	int32_t field_234;
	__padding char _238[8];
	__padding char _240[0x40];
	__padding char _280[0x28];
	int32_t field_2a8;
	int32_t field_2ac;
	int32_t field_2b0;
	int32_t field_2b4;
};

// "struct_133"
struct struct_133
{
	__padding char _0[0x40];
	__padding char _40[0x38];
	int32_t field_78;
};

// "struct_134"
struct struct_134
{
	__padding char _0[4];
	void* field_04;
};

// "struct_135"
struct struct_135
{
	int32_t field_00;
	__padding char _4[4];
	int32_t field_08;
	__padding char _C[8];
	int32_t field_14;
	int32_t field_18;
	__padding char _1C[4];
	__padding char _20[4];
	__padding char _24[0x1c];
	__padding char _40[0x14];
	__padding char _54[0x20];
	__padding char _74[0xc];
	__padding char _80[0x14];
	int32_t field_94;
	int32_t field_98;
	__padding char _9C[8];
	int32_t field_a4;
	int32_t field_a8;
	char field_ac;
	__padding char _B0[0xc];
	struct struct_148* field_bc;
	struct struct_144* field_c0;
	__padding char _C4[4];
	__padding char _C8[8];
	__padding char _D0[4];
	void* field_d4;
};

// "struct_136"
struct struct_136
{
	int32_t field_00;
};

// "struct_137"
struct struct_137
{
	__padding char _0[0x14];
	int32_t field_14;
	int32_t field_18;
	__padding char _1C[0x24];
	__padding char _40[0x14];
	__padding char _54[0x20];
	__padding char _74[0xc];
	__padding char _80[0x14];
	int32_t field_94;
	int32_t field_98;
	__padding char _9C[8];
	int32_t field_a4;
	int32_t field_a8;
	char field_ac;
	__padding char _B0[0xc];
	struct struct_136* field_bc;
	struct struct_135* field_c0;
	__padding char _C4[0x10];
	struct struct_142* field_d4;
};

// "struct_138"
struct struct_138
{
	void* field_00;
};

// "struct_139"
struct struct_139
{
	__padding char _0[0x14];
	int32_t field_14;
	int32_t field_18;
};

// "struct_14"
struct struct_14
{
	__padding char _0[0xc];
	int32_t field_0c;
};

// "struct_140"
struct struct_140
{
	int32_t field_00;
	int32_t field_04;
	__padding char _8[0x20];
	int32_t field_28;
	int32_t field_2c;
	__padding char _30[0x10];
	__padding char _40[0x10];
	int32_t field_50;
	int32_t field_54;
	__padding char _58[0x20];
	int32_t field_78;
	int32_t field_7c;
	__padding char _80[0x20];
	int32_t field_a0;
	int32_t field_a4;
	__padding char _A8[0x18];
	__padding char _C0[8];
	int32_t field_c8;
	int32_t field_cc;
	__padding char _D0[0x20];
	int32_t field_f0;
	int32_t field_f4;
	__padding char _F8[8];
	__padding char _100[0x18];
	int32_t field_118;
	int32_t field_11c;
};

// "struct_141"
struct struct_141
{
	int32_t field_00;
	int32_t field_04;
	__padding char _8[0x14];
	int32_t field_1c;
	int32_t field_20;
	__padding char _24[0x14];
	int32_t field_38;
	int32_t field_3c;
	__padding char _40[0x14];
	int32_t field_54;
	int32_t field_58;
	__padding char _5C[0x14];
	int32_t field_70;
	int32_t field_74;
	__padding char _78[8];
	__padding char _80[0xc];
	int32_t field_8c;
	int32_t field_90;
	__padding char _94[0x14];
	int32_t field_a8;
	int32_t field_ac;
	__padding char _B0[0x10];
	__padding char _C0[4];
	int32_t field_c4;
	int32_t field_c8;
	__padding char _CC[0x14];
	int32_t field_e0;
	int32_t field_e4;
	__padding char _E8[0x14];
	int32_t field_fc;
	int32_t field_100;
	__padding char _104[0x14];
	int32_t field_118;
	int32_t field_11c;
	__padding char _120[0x14];
	int32_t field_134;
	int32_t field_138;
	__padding char _13C[4];
	__padding char _140[0x10];
	int32_t field_150;
	int32_t field_154;
	__padding char _158[0x14];
	int32_t field_16c;
	int32_t field_170;
	__padding char _174[0xc];
	__padding char _180[8];
	int32_t field_188;
	int32_t field_18c;
	__padding char _190[0x14];
	int32_t field_1a4;
	int32_t field_1a8;
};

// "struct_142"
struct struct_142
{
	__padding char _0[8];
	int32_t field_08;
	int32_t field_0c;
	int32_t field_10;
	int32_t field_14;
	int32_t field_18;
	int32_t field_1c;
	int32_t field_20;
};

// "struct_143"
struct struct_143
{
	int32_t field_00;
};

// "struct_144"
struct struct_144
{
	int32_t field_00;
};

// "struct_145"
struct struct_145
{
	int32_t field_00;
};

// "struct_146"
struct struct_146
{
	int32_t field_00;
};

// "struct_147"
struct struct_147
{
	int32_t field_00;
};

// "struct_148"
struct struct_148
{
	int32_t field_00;
};

// "struct_149"
struct struct_149
{
	void* field_00;
};

// "struct_15"
struct struct_15
{
	__padding char _0[4];
	__padding char _4[0x3c];
	__padding char _40[0x24];
	__padding char _64[8];
	__padding char _6C[4];
	int32_t field_70;
};

// "struct_150"
struct struct_150
{
	int32_t field_00;
};

// "struct_151"
struct struct_151
{
	int32_t field_00;
};

// "struct_152"
struct struct_152
{
	__padding char _0[4];
	int32_t field_04;
	struct struct_153* field_08;
};

// "struct_153"
struct struct_153
{
	__padding char _0[0xc];
	int32_t field_0c;
};

// "struct_154"
struct struct_154
{
	int32_t field_00;
};

// "struct_155"
struct struct_155
{
	int32_t field_00;
};

// "struct_156"
struct struct_156
{
	int32_t field_00;
	void* field_04;
	struct struct_157* field_08;
};

// "struct_157"
struct struct_157
{
	__padding char _0[4];
	int32_t field_04;
	struct struct_158* field_08;
};

// "struct_158"
struct struct_158
{
	__padding char _0[0xc];
	int32_t field_0c;
};

// "struct_159"
struct struct_159
{
	int32_t field_00;
};

// "struct_16"
struct struct_16
{
	int32_t field_00;
	int32_t field_04;
	char field_08;
};

// "struct_160"
struct struct_160
{
	int32_t field_00;
	int32_t field_04;
	int32_t field_08;
};

// "struct_161"
struct struct_161
{
	__padding char _0[1];
	__padding char _1[3];
	struct struct_212* field_04;
	__padding char _8[4];
	__padding char _C[4];
	__padding char _10[4];
	__padding char _14[4];
	__padding char _18[4];
	__padding char _1C[4];
	int32_t field_20;
	int32_t field_24;
	int32_t field_28;
	int32_t field_2c;
	int32_t field_30;
	int32_t field_34;
	int32_t field_38;
};

// "struct_162"
struct struct_162
{
	__padding char _0[0xc];
	struct struct_162* field_0c;
};

// "struct_163"
struct struct_163
{
	__padding char _0[0xc];
	struct struct_163* field_0c;
};

// "struct_164"
struct struct_164
{
	__padding char _0[4];
	struct struct_189* field_04;
	__padding char _8[0xc];
	struct struct_164* field_14;
};

// "struct_165"
struct struct_165
{
	int32_t field_00;
	int32_t field_04;
	int32_t field_08;
};

// "struct_166"
struct struct_166
{
	int32_t field_00;
	int32_t field_04;
	int32_t field_08;
};

// "struct_167"
struct struct_167
{
	__padding char _0[4];
	struct struct_168* field_04;
};

// "struct_168"
struct struct_168
{
	__padding char _0[0x3c];
	int32_t field_3c;
	__padding char _40[4];
	int32_t field_44;
};

// "struct_169"
struct struct_169
{
	__padding char _0[0x40];
	__padding char _40[0x10];
	int32_t field_50;
};

// "struct_17"
struct struct_17
{
};

// "struct_170"
struct struct_170
{
	int32_t field_00;
	int32_t field_04;
	int32_t field_08;
};

// "struct_171"
struct struct_171
{
	int32_t field_00;
	int32_t field_04;
	int32_t field_08;
};

// "struct_172"
struct struct_172
{
	__padding char _0[0xc];
	struct struct_162* field_0c;
};

// "struct_173"
struct struct_173
{
	int32_t field_00;
	int32_t field_04;
	int32_t field_08;
};

// "struct_174"
struct struct_174
{
	int32_t field_00;
	int32_t field_04;
	int32_t field_08;
};

// "struct_175"
struct struct_175
{
	__padding char _0[0xc];
	struct struct_163* field_0c;
};

// "struct_176"
struct struct_176
{
	int32_t field_00;
	int32_t field_04;
	int32_t field_08;
};

// "struct_177"
struct struct_177
{
	int32_t field_00;
	int32_t field_04;
	int32_t field_08;
	int32_t field_0c;
	int32_t field_10;
	int32_t field_14;
	int32_t field_18;
	int32_t field_1c;
	int32_t field_20;
	int32_t field_24;
	int32_t field_28;
	int32_t field_2c;
	int32_t field_30;
	int32_t field_34;
	int32_t field_38;
	int32_t field_3c;
};

// "struct_178"
struct struct_178
{
	int32_t field_00;
	int32_t field_04;
	int32_t field_08;
	int32_t field_0c;
	int32_t field_10;
	int32_t field_14;
	int32_t field_18;
	int32_t field_1c;
	int32_t field_20;
	int32_t field_24;
	int32_t field_28;
	int32_t field_2c;
	int32_t field_30;
	int32_t field_34;
	int32_t field_38;
	int32_t field_3c;
};

// "struct_179"
struct struct_179
{
	int32_t field_00;
	int32_t field_04;
	int32_t field_08;
};

// "struct_18"
struct struct_18
{
	int32_t field_00;
};

// "struct_180"
struct struct_180
{
	int32_t field_00;
	int32_t field_04;
	int32_t field_08;
};

// "struct_181"
struct struct_181
{
	int32_t field_00;
	int32_t field_04;
	int32_t field_08;
};

// "struct_182"
struct struct_182
{
	int32_t field_00;
	int32_t field_04;
	int32_t field_08;
};

// "struct_183"
struct struct_183
{
	int32_t field_00;
	int32_t field_04;
	int32_t field_08;
};

// "struct_184"
struct struct_184
{
	int32_t field_00;
	int32_t field_04;
	int32_t field_08;
	int32_t field_0c;
	int32_t field_10;
	int32_t field_14;
	int32_t field_18;
	int32_t field_1c;
	int32_t field_20;
	int32_t field_24;
	int32_t field_28;
	int32_t field_2c;
	int32_t field_30;
	int32_t field_34;
	int32_t field_38;
	int32_t field_3c;
};

// "struct_185"
struct struct_185
{
	__padding char _0[4];
	struct struct_187* field_04;
	__padding char _8[8];
	struct struct_164* field_10;
	__padding char _14[4];
	__padding char _18[4];
	__padding char _1C[4];
	int32_t field_20;
	int32_t field_24;
	int32_t field_28;
	int32_t field_2c;
	int32_t field_30;
	int32_t field_34;
	int32_t field_38;
};

// "struct_186"
struct struct_186
{
	char field_00;
	struct struct_188* field_04;
	__padding char _8[4];
	__padding char _C[4];
	__padding char _10[4];
	__padding char _14[4];
	__padding char _18[4];
	__padding char _1C[4];
	int32_t field_20;
	int32_t field_24;
	int32_t field_28;
	int32_t field_2c;
	int32_t field_30;
	int32_t field_34;
	int32_t field_38;
};

// "struct_187"
struct struct_187
{
	__padding char _0[0x40];
	__padding char _40[0x20];
	int32_t field_60;
};

// "struct_188"
struct struct_188
{
	__padding char _0[0x40];
	__padding char _40[0x1c];
	int32_t field_5c;
};

// "struct_189"
struct struct_189
{
	__padding char _0[0x20];
	int32_t field_20;
};

// "struct_19"
struct struct_19
{
	__padding char _0[1];
	__padding char _1[0xf];
	__padding char _10[4];
	__padding char _14[4];
	__padding char _18[4];
	__padding char _1C[4];
	__padding char _20[0x10];
	__padding char _30[0xc];
	__padding char _3C[4];
	__padding char _40[0x40];
	__padding char _80[0x40];
	__padding char _C0[0x40];
	__padding char _100[0x40];
	__padding char _140[0x40];
	__padding char _180[0x40];
	__padding char _1C0[0x40];
	__padding char _200[0x40];
	__padding char _240[0x40];
	__padding char _280[0x28];
	int32_t field_2a8;
	int32_t field_2ac;
	int32_t field_2b0;
	int32_t field_2b4;
	int32_t field_2b8;
	int32_t field_2bc;
	int32_t field_2c0;
	int32_t field_2c4;
	__padding char _2C8[4];
	int32_t field_2cc;
	int32_t field_2d0;
};

// "struct_190"
struct struct_190
{
	int32_t field_00;
	int32_t field_04;
	int32_t field_08;
	int32_t field_0c;
	int32_t field_10;
	int32_t field_14;
	int32_t field_18;
	int32_t field_1c;
};

// "struct_191"
struct struct_191
{
	int32_t field_00;
};

// "struct_192"
struct struct_192
{
	int32_t field_00;
};

// "struct_193"
struct struct_193
{
	__padding char _0[4];
	struct struct_194* field_04;
};

// "struct_194"
struct struct_194
{
	__padding char _0[0x40];
	__padding char _40[0x18];
	int32_t field_58;
};

// "struct_195"
struct struct_195
{
	__padding char _0[0xc];
	struct struct_161* field_0c;
	__padding char _10[4];
	__padding char _14[4];
	__padding char _18[4];
	__padding char _1C[4];
	__padding char _20[4];
	__padding char _24[4];
	char field_28;
	__padding char _2C[0x14];
	__padding char _40[0x14];
	int32_t field_54;
	struct struct_215* field_58;
	struct struct_213* field_5c;
	__padding char _60[4];
	int32_t field_64;
};

// "struct_196"
struct struct_196
{
	int32_t field_00;
	int32_t field_04;
	void* field_08;
	__padding char _C[4];
	struct struct_198* field_10;
};

// "struct_197"
struct struct_197
{
	int32_t field_00;
};

// "struct_198"
struct struct_198
{
	__padding char _0[8];
	struct struct_217* field_08;
};

// "struct_199"
struct struct_199
{
	char field_00;
	char field_01;
	void* field_04;
};

// "struct_2"
struct struct_2
{
	int32_t field_00;
	int32_t field_04;
	int32_t field_08;
	int32_t field_0c;
	int32_t field_10;
	int32_t field_14;
	int32_t field_18;
	int32_t field_1c;
	int32_t field_20;
	int32_t field_24;
	__padding char _28[4];
	int32_t field_2c;
	int32_t field_30;
	int32_t field_34;
	int32_t field_38;
};

// "struct_20"
struct struct_20
{
	__padding char _0[0x10];
	int32_t field_10;
	int32_t field_14;
	int32_t field_18;
	int32_t field_1c;
	int32_t field_20;
	int32_t field_24;
	char field_28;
	__padding char _29[0x17];
	__padding char _40[0x20];
	char field_60;
	int32_t field_64;
	char field_68;
	int32_t field_6c;
};

// "struct_200"
struct struct_200
{
	int32_t field_00;
	int32_t field_04;
	int32_t field_08;
	int32_t field_0c;
	int32_t field_10;
	int32_t field_14;
	int32_t field_18;
	char field_1c;
	void* field_20;
	void* field_24;
	int32_t field_28;
	int32_t field_2c;
	char field_30;
	char field_31;
	int32_t field_34;
};

// "struct_201"
struct struct_201
{
	__padding char _0[0xc];
	int32_t field_0c;
};

// "struct_202"
struct struct_202
{
	__padding char _0[0x40];
	__padding char _40[0x40];
	__padding char _80[0x40];
	__padding char _C0[0x40];
	__padding char _100[0x40];
	__padding char _140[0x40];
	__padding char _180[0x40];
	__padding char _1C0[0x40];
	__padding char _200[0x40];
	__padding char _240[0x40];
	__padding char _280[0x28];
	int32_t field_2a8;
	int32_t field_2ac;
	int32_t field_2b0;
	int32_t field_2b4;
};

// "struct_203"
struct struct_203
{
	__padding char _0[0x40];
	int32_t field_40;
};

// "struct_204"
struct struct_204
{
	__padding char _0[0x40];
	__padding char _40[0x34];
	__padding char _74[0xc];
	__padding char _80[0x40];
	__padding char _C0[0x40];
	__padding char _100[0x40];
	__padding char _140[0x40];
	__padding char _180[0x40];
	__padding char _1C0[0x40];
	__padding char _200[0x40];
	__padding char _240[0x40];
	__padding char _280[0x40];
	__padding char _2C0[0x40];
	__padding char _300[0x40];
	__padding char _340[0x40];
	__padding char _380[0x40];
	__padding char _3C0[0x40];
	__padding char _400[0x40];
	__padding char _440[0x40];
	__padding char _480[0x40];
	__padding char _4C0[0x40];
	__padding char _500[0x40];
	__padding char _540[0x40];
	__padding char _580[0x40];
	__padding char _5C0[0x40];
	__padding char _600[0x40];
	__padding char _640[0x40];
	__padding char _680[0x40];
	__padding char _6C0[0x40];
	__padding char _700[0x40];
	__padding char _740[0x40];
	__padding char _780[0x40];
	__padding char _7C0[0x40];
	__padding char _800[0x40];
	__padding char _840[0x40];
	__padding char _880[0x40];
	__padding char _8C0[0x40];
	__padding char _900[0x40];
	__padding char _940[0x2c];
	int32_t field_96c;
	int32_t field_970;
	int32_t field_974;
};

// "struct_205"
struct struct_205
{
	__padding char _0[4];
	int32_t field_04;
	int32_t field_08;
};

// "struct_206"
struct struct_206
{
	void* field_00;
	void* field_04;
	void* field_08;
	void* field_0c;
	int16_t field_10;
	__padding char _14[0x2c];
	__padding char _40[0x10];
	int32_t field_50;
	int32_t field_54;
	int32_t field_58;
	int32_t field_5c;
	__padding char _60[0x20];
	__padding char _80[0x20];
	int32_t field_a0;
	int32_t field_a4;
	int32_t field_a8;
	int32_t field_ac;
	__padding char _B0[0x10];
	__padding char _C0[0x30];
	int32_t field_f0;
	int32_t field_f4;
	int32_t field_f8;
	int32_t field_fc;
	__padding char _100[0x40];
	int32_t field_140;
	int32_t field_144;
	int32_t field_148;
	int32_t field_14c;
	__padding char _150[0x30];
	__padding char _180[0x10];
	int32_t field_190;
	int32_t field_194;
	int32_t field_198;
	int32_t field_19c;
	__padding char _1A0[0x20];
	__padding char _1C0[0x20];
	int32_t field_1e0;
	int32_t field_1e4;
	int32_t field_1e8;
	int32_t field_1ec;
	__padding char _1F0[0x10];
	__padding char _200[0x30];
	int32_t field_230;
	int32_t field_234;
	int32_t field_238;
	int32_t field_23c;
};

// "struct_207"
struct struct_207
{
	void* field_00;
	void* field_04;
	void* field_08;
	void* field_0c;
	struct struct_208* field_10;
};

// "struct_208"
struct struct_208
{
	char field_00;
};

// "struct_209"
struct struct_209
{
	__padding char _0[1];
	__padding char _1[3];
	__padding char _4[0xc];
	__padding char _10[0xc];
	__padding char _1C[4];
	__padding char _20[4];
	__padding char _24[4];
	__padding char _28[4];
	__padding char _2C[4];
	__padding char _30[4];
	__padding char _34[4];
	__padding char _38[8];
	__padding char _40[0x2c];
	__padding char _6C[0xc];
	struct struct_210* field_78;
};

// "struct_21"
struct struct_21
{
	__padding char _0[4];
	int32_t field_04;
	int32_t field_08;
};

// "struct_210"
struct struct_210
{
	__padding char _0[4];
	__padding char _4[0x3c];
	__padding char _40[0x40];
	__padding char _80[0x40];
	__padding char _C0[0x40];
	__padding char _100[0x40];
	__padding char _140[0x40];
	__padding char _180[0x40];
	__padding char _1C0[0x40];
	__padding char _200[0x40];
	__padding char _240[0x40];
	__padding char _280[0x40];
	__padding char _2C0[0x40];
	__padding char _300[0x40];
	__padding char _340[0x40];
	__padding char _380[0x40];
	__padding char _3C0[0x40];
	__padding char _400[0x40];
	__padding char _440[0x40];
	__padding char _480[0x40];
	__padding char _4C0[0x40];
	__padding char _500[0x40];
	__padding char _540[0x40];
	__padding char _580[0x40];
	__padding char _5C0[0x40];
	__padding char _600[0x40];
	__padding char _640[0x40];
	__padding char _680[0x40];
	__padding char _6C0[0x40];
	__padding char _700[0x40];
	__padding char _740[0x40];
	__padding char _780[0x40];
	__padding char _7C0[0x40];
	__padding char _800[0x40];
	__padding char _840[0x40];
	__padding char _880[0x40];
	__padding char _8C0[0x40];
	__padding char _900[0x40];
	__padding char _940[0x40];
	__padding char _980[0x40];
	__padding char _9C0[0x40];
	__padding char _A00[0x40];
	__padding char _A40[0x40];
	__padding char _A80[0x40];
	__padding char _AC0[0x40];
	__padding char _B00[0x40];
	__padding char _B40[0x40];
	__padding char _B80[0x40];
	__padding char _BC0[0x40];
	__padding char _C00[0x40];
	__padding char _C40[0x40];
	__padding char _C80[0x40];
	__padding char _CC0[0x40];
	__padding char _D00[0x40];
	__padding char _D40[0x40];
	__padding char _D80[0x3c];
	int32_t field_dbc;
};

// "struct_211"
struct struct_211
{
	__padding char _0[0x40];
	__padding char _40[0x14];
	void* field_54;
	int32_t field_58;
	int32_t field_5c;
};

// "struct_212"
struct struct_212
{
	__padding char _0[0xc];
	__padding char _C[0xc];
	__padding char _18[0x18];
	__padding char _30[0x10];
	__padding char _40[8];
	__padding char _48[8];
	__padding char _50[8];
	__padding char _58[4];
	__padding char _5C[4];
	int32_t field_60;
};

// "struct_213"
struct struct_213
{
	__padding char _0[4];
	struct struct_214* field_04;
	int32_t field_08;
};

// "struct_214"
struct struct_214
{
	__padding char _0[0x38];
	int32_t field_38;
};

// "struct_215"
struct struct_215
{
	__padding char _0[4];
	struct struct_216* field_04;
	int32_t field_08;
};

// "struct_216"
struct struct_216
{
	__padding char _0[0x38];
	int32_t field_38;
};

// "struct_217"
struct struct_217
{
	__padding char _0[0x10];
	int32_t field_10;
};

// "struct_218"
struct struct_218
{
	void* field_00;
	int32_t field_04;
};

// "struct_219"
struct struct_219
{
	void* field_00;
	int32_t field_04;
};

// "struct_22"
struct struct_22
{
	char field_00;
};

// "struct_23"
struct struct_23
{
	char field_00;
};

// "struct_24"
struct struct_24
{
	int32_t field_00;
	int32_t field_04;
	int32_t field_08;
	int32_t field_0c;
};

// "struct_25"
struct struct_25
{
	__padding char _0[8];
	int32_t field_08;
};

// "struct_26"
struct struct_26
{
	char field_00;
	__padding char _4[0x3c];
	__padding char _40[0x40];
	__padding char _80[0x40];
	__padding char _C0[0x40];
	__padding char _100[0x40];
	__padding char _140[0x18];
	void* field_158;
	int32_t field_15c;
};

// "struct_27"
struct struct_27
{
	int32_t field_00;
	int32_t field_04;
	struct struct_42* field_08;
	int32_t field_0c;
	struct struct_27* field_10;
};

// "struct_28"
struct struct_28
{
	int32_t field_00;
	int32_t field_04;
	int32_t field_08;
	int32_t field_0c;
};

// "struct_29"
struct struct_29
{
	int32_t field_00;
	int32_t field_04;
	int32_t field_08;
	int32_t field_0c;
};

// "struct_3"
struct struct_3
{
	__padding char _0[0x14];
	struct struct_3* field_14;
};

// "struct_30"
struct struct_30
{
	int32_t field_00;
	int32_t field_04;
	int32_t field_08;
};

// "struct_31"
struct struct_31
{
	__padding char _0[1];
	__padding char _1[3];
	__padding char _4[4];
	int32_t field_08;
	__padding char _C[4];
	struct struct_3* field_10;
};

// "struct_32"
struct struct_32
{
	struct struct_34* field_00;
};

// "struct_33"
struct struct_33
{
	int32_t field_00;
	__padding char _4[4];
	struct struct_39* field_08;
	__padding char _C[4];
	struct NodeLevel3Alternate* field_10;
};

// "struct_34"
struct struct_34
{
	__padding char _0[0x40];
	__padding char _40[0x24];
	int32_t field_64;
	__padding char _68[0x10];
	struct struct_36* field_78;
};

// "struct_35"
struct struct_35
{
	int32_t field_00;
	__padding char _4[4];
	int32_t field_08;
	__padding char _C[4];
	int32_t field_10;
};

// "struct_36"
struct struct_36
{
	__padding char _0[8];
	int32_t field_08;
};

// "struct_37"
struct struct_37
{
	__padding char _0[4];
	__padding char _4[4];
	__padding char _8[4];
	struct struct_41* field_0c;
};

// "struct_38"
struct struct_38
{
	int32_t field_00;
	__padding char _4[4];
	struct struct_42* field_08;
	__padding char _C[4];
	struct NodeLevel2Tertiary* field_10;
};

// "struct_39"
struct struct_39
{
	int32_t field_00;
	__padding char _4[4];
	int32_t field_08;
	__padding char _C[4];
	int32_t field_10;
};

// "struct_4"
struct struct_4
{
	__padding char _0[4];
	struct struct_1* field_04;
};

// "struct_40"
struct struct_40
{
	int32_t field_00;
	__padding char _4[4];
	int32_t field_08;
	__padding char _C[4];
	int32_t field_10;
};

// "struct_41"
struct struct_41
{
	__padding char _0[0xc];
	int32_t field_0c;
};

// "struct_42"
struct struct_42
{
	int32_t field_00;
	__padding char _4[4];
	int32_t field_08;
	__padding char _C[4];
	int32_t field_10;
};

// "struct_43"
struct struct_43
{
	__padding char _0[4];
	int32_t field_04;
};

// "struct_44"
struct struct_44
{
	void* field_00;
	int32_t field_04;
};

// "struct_45"
struct struct_45
{
	void* field_00;
	int32_t field_04;
};

// "struct_46"
struct struct_46
{
	__padding char _0[4];
	void* field_04;
	int32_t field_08;
	void* field_0c;
	void* field_10;
	int32_t field_14;
	char field_18;
	int32_t field_1c;
	int32_t field_20;
	void* field_24;
	void* field_28;
	__padding char _2C[4];
	int32_t field_30;
	void* field_34;
	int32_t field_38;
	int32_t field_3c;
	void* field_40;
	void* field_44;
	__padding char _48[4];
	int32_t field_4c;
	void* field_50;
	int32_t field_54;
};

// "struct_47"
struct struct_47
{
	__padding char _0[4];
	int32_t field_04;
	int32_t field_08;
};

// "struct_48"
struct struct_48
{
	__padding char _0[8];
	int32_t field_08;
};

// "struct_49"
struct struct_49
{
	__padding char _0[8];
	int32_t field_08;
};

// "struct_5"
struct struct_5
{
	int32_t field_00;
	int32_t field_04;
	int32_t field_08;
};

// "struct_50"
struct struct_50
{
	char field_00;
};

// "struct_51"
struct struct_51
{
	char field_00;
};

// "struct_52"
struct struct_52
{
	int32_t field_00;
	void* field_04;
	int32_t field_08;
	void* field_0c;
	__padding char _10[0x10];
	void* field_20;
};

// "struct_53"
struct struct_53
{
	__padding char _0[0x18];
	int32_t field_18;
	int32_t field_1c;
	int32_t field_20;
	void* field_24;
	__padding char _28[8];
	int32_t field_30;
	void* field_34;
	int32_t field_38;
	struct struct_82* field_3c;
	__padding char _40[0x40];
	__padding char _80[0x40];
	__padding char _C0[0x40];
	__padding char _100[0x40];
	__padding char _140[0x40];
	__padding char _180[0x40];
	__padding char _1C0[0x40];
	__padding char _200[0x40];
	__padding char _240[0x40];
	__padding char _280[0x40];
	__padding char _2C0[0x40];
	__padding char _300[0x40];
	__padding char _340[0x40];
	__padding char _380[0x40];
	__padding char _3C0[0x40];
	__padding char _400[0x40];
	__padding char _440[0x40];
	__padding char _480[0x40];
	__padding char _4C0[0x40];
	__padding char _500[0x40];
	__padding char _540[0x40];
	__padding char _580[0x40];
	__padding char _5C0[0x40];
	__padding char _600[0x40];
	__padding char _640[0x40];
	__padding char _680[0x40];
	__padding char _6C0[0x40];
	__padding char _700[0x40];
	__padding char _740[0x40];
	__padding char _780[0x40];
	__padding char _7C0[0x40];
	__padding char _800[0x40];
	__padding char _840[0x40];
	__padding char _880[0x40];
	__padding char _8C0[0x40];
	__padding char _900[0x40];
	__padding char _940[0x40];
	__padding char _980[0x40];
	__padding char _9C0[0x40];
	__padding char _A00[0x40];
	__padding char _A40[0x40];
	__padding char _A80[0x40];
	__padding char _AC0[0x40];
	__padding char _B00[0x40];
	__padding char _B40[0x40];
	__padding char _B80[0x40];
	__padding char _BC0[0x40];
	__padding char _C00[0x40];
	__padding char _C40[0x40];
	__padding char _C80[0x40];
	__padding char _CC0[0x40];
	__padding char _D00[0x40];
	__padding char _D40[0x40];
	__padding char _D80[0x24];
	int32_t field_da4;
	int32_t field_da8;
	void* field_dac;
	void* field_db0;
	int32_t field_db4;
};

// "struct_54"
struct struct_54
{
	__padding char _0[4];
	int32_t field_04;
	void* field_08;
	__padding char _C[4];
	void* field_10;
};

// "struct_55"
struct struct_55
{
	int32_t field_00;
	int32_t field_04;
	int32_t field_08;
	int32_t field_0c;
};

// "struct_56"
struct struct_56
{
	int32_t field_00;
	int32_t field_04;
	int32_t field_08;
	int32_t field_0c;
};

// "struct_57"
struct struct_57
{
	int32_t field_00;
	int32_t field_04;
	int32_t field_08;
	int32_t field_0c;
};

// "struct_58"
struct struct_58
{
	int32_t field_00;
	int32_t field_04;
	int32_t field_08;
	int32_t field_0c;
};

// "struct_59"
struct struct_59
{
	int32_t field_00;
	int32_t field_04;
	int32_t field_08;
	int32_t field_0c;
};

// "struct_6"
struct struct_6
{
	int32_t field_00;
	__padding char _4[0x10];
	struct struct_7* field_14;
	void* field_18;
};

// "struct_60"
struct struct_60
{
	int32_t field_00;
	int32_t field_04;
	int32_t field_08;
};

// "struct_61"
struct struct_61
{
	int32_t field_00;
	int32_t field_04;
	int32_t field_08;
	int32_t field_0c;
};

// "struct_62"
struct struct_62
{
	int32_t field_00;
	int32_t field_04;
	int32_t field_08;
	int32_t field_0c;
};

// "struct_63"
struct struct_63
{
	int32_t field_00;
	int32_t field_04;
	int32_t field_08;
	int32_t field_0c;
};

// "struct_64"
struct struct_64
{
	int32_t field_00;
	int32_t field_04;
	int32_t field_08;
	int32_t field_0c;
	int32_t field_10;
	int32_t field_14;
	int32_t field_18;
	int32_t field_1c;
	int32_t field_20;
	int32_t field_24;
	int32_t field_28;
	int32_t field_2c;
};

// "struct_65"
struct struct_65
{
	int32_t field_00[0x1];
	int32_t field_04;
	int32_t field_08;
	int32_t field_0c;
};

// "struct_66"
struct struct_66
{
	__padding char _0[1];
	__padding char _1[2];
	char field_03;
	char field_04;
	struct struct_66* field_08;
	struct struct_66* field_0c;
	struct struct_66* field_10;
};

// "struct_68"
struct struct_68
{
	__padding char _0[8];
	struct struct_68* field_08;
};

// "struct_69"
struct struct_69
{
	struct struct_66* field_00;
};

// "struct_7"
struct struct_7
{
	__padding char _0[4];
	void* field_04;
};

// "struct_70"
struct struct_70
{
	void* field_00;
};

// "struct_71"
struct struct_71
{
	char field_00;
	char field_01;
	int32_t field_04;
};

// "struct_72"
struct struct_72
{
	char field_00;
	char field_01;
	int32_t field_04;
};

// "struct_73"
struct struct_73
{
	char field_00;
	char field_01;
	char field_02;
};

// "struct_74"
struct struct_74
{
	__padding char _0[0xc];
	int32_t field_0c;
	__padding char _10[0x20];
	int32_t field_30;
	int32_t field_34;
	int32_t field_38;
};

// "struct_75"
struct struct_75
{
	__padding char _0[0xc];
	int32_t field_0c;
	__padding char _10[0x20];
	int32_t field_30;
	int32_t field_34;
	int32_t field_38;
};

// "struct_76"
struct struct_76
{
	int32_t field_00;
	__padding char _4[4];
	struct TeamController* field_08;
	__padding char _C[4];
	int32_t field_10;
};

// "struct_77"
struct struct_77
{
	int32_t field_00;
	__padding char _4[4];
	struct struct_80* field_08;
	__padding char _C[4];
	struct NodeLevel2Tertiary* field_10;
};

// "struct_78"
struct struct_78
{
	int32_t field_00;
	__padding char _4[4];
	struct TeamController* field_08;
	__padding char _C[4];
	int32_t field_10;
};

// "struct_79"
struct struct_79
{
	int32_t field_00;
	__padding char _4[4];
	struct TeamController* field_08;
	__padding char _C[4];
	int32_t field_10;
};

// "struct_8"
struct struct_8
{
	__padding char _0[4];
	__padding char _4[4];
	int32_t field_08;
	__padding char _C[0x10];
	__padding char _1C[0x24];
	__padding char _40[0x24];
	__padding char _64[0xc];
	int32_t field_70;
};

// "struct_80"
struct struct_80
{
	int32_t field_00;
	__padding char _4[4];
	struct TeamController* field_08;
	__padding char _C[4];
	int32_t field_10;
};

// "struct_81"
struct struct_81
{
	__padding char _0[4];
	int32_t field_04;
	int32_t field_08;
};

// "struct_82"
struct struct_82
{
	__padding char _0[4];
	int32_t field_04;
	struct struct_83* field_08;
};

// "struct_83"
struct struct_83
{
	__padding char _0[0xc];
	int32_t field_0c;
};

// "struct_84"
struct struct_84
{
	void* field_00;
};

// "struct_85"
struct struct_85
{
	void* field_00;
	__padding char _4[0x3c];
	__padding char _40[0x14];
	void* field_54;
	__padding char _58[0x28];
	__padding char _80[0xc];
	void* field_8c;
	void* field_90;
	int32_t field_94;
	int32_t field_98;
	void* field_9c;
	__padding char _A0[4];
	void* field_a4;
	int32_t field_a8;
	__padding char _AC[0x14];
	__padding char _C0[0x40];
	__padding char _100[0x40];
	__padding char _140[0x40];
	__padding char _180[0x2c];
	int32_t field_1ac;
};

// "struct_86"
struct struct_86
{
	int32_t field_00;
};

// "struct_87"
struct struct_87
{
	int32_t field_00;
};

// "struct_88"
struct struct_88
{
	int32_t field_00;
};

// "struct_89"
struct struct_89
{
	int32_t field_00;
};

// "struct_9"
struct struct_9
{
	int32_t field_00;
	void* field_04;
	struct struct_10* field_08;
};

// "struct_90"
struct struct_90
{
	__padding char _0[0xc];
	int32_t field_0c;
	char* field_10;
	char* field_14;
	struct struct_91* field_18;
};

// "struct_91"
struct struct_91
{
	__padding char _0[4];
	int32_t field_04;
	struct struct_92* field_08;
};

// "struct_92"
struct struct_92
{
	__padding char _0[0xc];
	int32_t field_0c;
};

// "struct_93"
struct struct_93
{
	int32_t field_00;
	int32_t field_04;
	int32_t field_08;
	int32_t field_0c;
	int32_t field_10;
	int32_t field_14;
};

// "struct_94"
struct struct_94
{
	__padding char _0[1];
	__padding char _1[7];
	int32_t field_08;
	int32_t field_0c;
};

// "struct_95"
struct struct_95
{
	int32_t field_00;
	char field_04;
	int32_t field_08;
	int32_t field_0c;
	int32_t field_10;
	int32_t field_14;
	int32_t field_18;
};

// "struct_96"
struct struct_96
{
	__padding char _0[4];
	void* field_04;
};

// "struct_97"
struct struct_97
{
	__padding char _0[4];
	struct struct_99* field_04;
};

// "struct_98"
struct struct_98
{
	char field_00;
	char field_01;
	char field_02;
	char field_03;
};

// "struct_99"
struct struct_99
{
	__padding char _0[0x40];
	__padding char _40[0x40];
	__padding char _80[0x3c];
	int32_t field_bc;
	int32_t field_c0;
};

